version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.4.0
    steps:
      - checkout
      - run: npm i --verbose
      - run: sudo npm i -g codecov
      - run: npm test -- --coverage
      - run: codecov
      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy:
    docker:
      - image: circleci/node:10.4.0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
#       - run: npm publish
#       - run:     command: |
#       if [ "${CIRCLE_BRANCH}" == "master" ]; then
#         ansible-playbook site.yml
#       fi  
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          branches:
            only: /master/
