version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.4.0
    steps:
      - checkout
      - run: npm i --verbose
      - run: sudo npm i -g codecov
      - run: npm test -- --coverage
      - run: codecov
      - store_artifacts:
          path: coverage
          prefix: coverage
  publish:
    docker:
      - image: circleci/node:10.4.0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
#       - run: npm publish  
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          branches:
            only:
              - master
#           requires:
#             - test
# #           filters:
#               branches:
#               only: master
