version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts-jessie
    steps:
      - checkout
      - run: npm i --verbose
      - run: sudo npm i -g codecov
      - run: npm test -- --coverage
      - run: codecov
      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy:
    docker:
      - image: circleci/node:lts-jessie
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
             npm publish
          fi  
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy
#           requires:
#             - test
#           branches:
#             only: /master/
